# https://llvm.org/docs/Passes.html#codegenprepare-optimize-for-code-generation
potential_passes = [
    "adce",
    "aggressive-instcombine",
    "bdce",
    # "called-value-propagation",
    # "cg-profile",
    "constraint-elimination",
    # "coro-cleanup",
    # "coro-early",
    # "coro-elide",
    "correlated-propagation",
    # "deadargelim",
    "div-rem-pairs",
    "dse",
    "early-cse",
    # "elim-avail-extern",
    # "forceattrs",
    # "function(annotation-remarks)",
    "function(early-cse)",
    "function(instcombine)",
    "function(lower-expect)",
    "function(simplifycfg)",
    "function(sroa)",
    # "function-attrs",
    # "globaldce",
    # "globalopt",
    "gvn",
    # "inferattrs",
    "inject-tli-mappings",
    # "inline",
    "instcombine",
    "instsimplify",
    # "ipsccp",
    "jump-threading",
    "indvars",
    "loop-deletion",
    "loop-idiom",
    "loop-unroll-full",
    "loop-distribute",
    "loop-load-elim",
    "loop-mssa(licm)",
    "loop-instsimplify",
    "loop-rotate",
    "loop-simplifycfg",
    "simple-loop-unswitch",
    "loop-sink",
    "loop-unroll",
    "loop-vectorize",
    "lower-constant-intrinsics",
    "memcpyopt",
    "mldst-motion",
    "move-auto-init",
    # "openmp-opt",
    "reassociate",
    # "recompute-globalsaa",
    # "rel-lookup-table-converter",
    # "rpo-function-attrs",
    "sccp",
    "simplifycfg",
    "slp-vectorizer",
    "speculative-execution",
    "sroa",
    "tailcallelim",
    "transform-warning",
    "vector-combine",
    "verify",
]